[project]
name = "dz-catalog-analysis-zadorozhnii-m26-555"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Xlemon5", email = "80254502+Xlemon5@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
dz-catalog-analysis-zadorozhnii-m26-555 = "dz_catalog_analysis_zadorozhnii_m26_555:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.8",
]

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["venv", ".venv", "dist", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []